// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TemplateApi.Models;

#nullable disable

namespace TemplateApi.Migrations
{
    [DbContext(typeof(TemplateContext))]
    [Migration("20241028014906_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TemplateApi.Models.Table1", b =>
                {
                    b.Property<int>("Table1Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Table1Id"));

                    b.Property<string>("Column1")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Table1Id");

                    b.ToTable("Table1");
                });
#pragma warning restore 612, 618
        }
    }
}
